[tool.black]
line-length = 120
target-version = ['py38']

[tool.mypy]
python_version = "3.8"
strict_optional = true
disallow_untyped_defs = true
disallow_untyped_calls = true
ignore_missing_imports = true
